### ISSUE TITLE
[Feature Request] Migrating tensorspecs back into tensordict

### ISSUE THREAD

**Issue by theOGognf** [pytorch-labs/tensordict#406]
## Motivation

This is a separate issue following [a couple of comments from the Kill tensorspec PR](https://github.com/pytorch-labs/tensordict/pull/2#issuecomment-1575578417). Without repeating the comments, there's some desire to migrate tensorspecs back into tensordict because:

1. tensorspecs and tensordicts naturally go together (even outside the context of RL)
2. [tensorspecs have little-to-no dependency on the rest of the torchrl package](https://github.com/pytorch/rl/blob/340d47e95deda221562387f6b47846513c71a4a6/torchrl/data/tensor_specs.py#L37)
3. torchrl is a larger package that has [limited PyTorch version support](https://github.com/pytorch/rl/issues/975)

## Solution

1. Move tensorspecs back into tensordict
2. Change torchrl's tensorspecs to point to tensordict's tensorspecs (irrelevant to this project)

## Alternatives

Leave tensorspec where it is and have users continue installing torchrl as an additional dependency if they want to use tensorspecs with tensordicts.

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by theOGognf** [comment]
@vmoens Was there internal discussion on this issue?

**Comment by matteobettini** [comment]
This is an interesting problem that I have also found myself thinking about.
Both solutions have certainly some pros and cons.

Here are some of my thoughts:
- Although specs are useful in some contexts outside RL, they are still not applicable in all the contexts where tensordict can be applied. Having them in tensordict might cause some confusion for tensordict users. This is because if we decide to bring them back, we would have also to transfer SafeModules and other tensordictmodules that check their output against specs. The question then is where to draw the boundary? It may reduce the modularity of tensordict
- The development of specs is very tied to the RL repo. For example, the decision of what specs to implement, what functions they possess and so on, is driven by their RL uscases.
- Specs are not necessarily tied to tensordicts. They actually define the domains of tensors. If they were fortunate enough to make it to pytorch core, they should not be part of the tensordict module, but have more generality. Therefore, tying them to this module might be somewhat limiting as they pertain to tensors, not necessaily to dicts. 

Here is why I am not totally on board to move them here.
What do you think?

**Comment by theOGognf** [comment]
> * Specs are not necessarily tied to tensordicts. They actually define the domains of tensors. If they were fortunate enough to make it to pytorch core, they should not be part of the tensordict module, but have more generality. Therefore, tying them to this module might be somewhat limiting as they pertain to tensors, not necessaily to dicts.

All good points, but this one especially resonated. That's good reasoning to not merge specs back in (in hope of specs - and also tensordicts - making it into core). I'm fine closing this issue. Thanks for the thoughts

**Comment by vmoens** [comment]
Closing for now, feel free to reopen if needed
